"""Weekly report generator: uses the gateway autonomous-scan endpoint."""

from __future__ import annotations

import logging
import os
import re
from datetime import UTC, datetime

from src.config import settings

logger = logging.getLogger(__name__)


async def generate_report(period_start: str, period_end: str | None = None) -> dict:
    end = period_end or datetime.now(UTC).strftime("%Y-%m-%d")

    # Delegate to gateway's autonomous-scan, which owns the local LLM client.
    import aiohttp

    prompt = (
        f"Generate a comprehensive weekly investment report for {period_start} to {end}. "
        "Structure it with: Executive Summary, Portfolio Overview, Trades, Market Analysis "
        "(stocks, crypto, macro), Thesis Updates, Upcoming Catalysts, Simulation Results, "
        "Agent Reasoning Audit. Use all available tools to fetch real data."
    )

    full_text = ""
    try:
        async with aiohttp.ClientSession(timeout=aiohttp.ClientTimeout(total=300)) as s:
            async with s.post(
                f"{settings.gateway_url}/api/autonomous-scan",
                json={"prompt": prompt},
            ) as resp:
                if resp.status == 200:
                    data = await resp.json()
                    full_text = data.get("summary", "Report generation pending.")
    except Exception as exc:
        logger.warning("Gateway report request failed: %s", exc)
        full_text = f"Report generation failed: {exc}"

    html_content = _wrap_html(full_text, period_start, end)

    pdf_path = None
    try:
        import weasyprint

        os.makedirs(settings.reports_dir, exist_ok=True)
        pdf_filename = f"report_{period_start}_{end}.pdf"
        pdf_path = os.path.join(settings.reports_dir, pdf_filename)
        weasyprint.HTML(string=html_content).write_pdf(pdf_path)
        logger.info("Report PDF saved: %s", pdf_path)
    except Exception as exc:
        logger.warning("PDF generation failed: %s", exc)

    report_id = None
    try:
        from src.db.database import async_session
        from src.db.models import Report

        async with async_session() as session:
            report = Report(
                title=f"Weekly Investment Report {period_start} – {end}",
                period_start=datetime.fromisoformat(period_start).replace(tzinfo=UTC),
                period_end=datetime.fromisoformat(end).replace(tzinfo=UTC),
                html_content=html_content,
                pdf_path=pdf_path,
            )
            session.add(report)
            await session.commit()
            report_id = report.id
    except Exception as exc:
        logger.warning("Failed to persist report: %s", exc)

    return {
        "success": True,
        "report_id": report_id,
        "period_start": period_start,
        "period_end": end,
        "pdf_path": pdf_path,
    }


def _wrap_html(markdown: str, period_start: str, end: str) -> str:
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Investment Report {period_start} to {end}</title>
<style>
  body {{ font-family: Georgia, serif; max-width: 900px; margin: 40px auto; padding: 0 20px;
         color: #1a1a2e; line-height: 1.7; }}
  h1 {{ color: #0f3460; border-bottom: 3px solid #e94560; padding-bottom: 10px; }}
  h2 {{ color: #16213e; margin-top: 40px; }}
  h3 {{ color: #0f3460; }}
  .disclaimer {{ font-size: 0.85em; color: #666; border-top: 1px solid #ddd;
                 margin-top: 40px; padding-top: 20px; }}
</style>
</head>
<body>
{_md_to_html(markdown)}
<div class="disclaimer">
  Generated by Investment Assistant AI. Not financial advice.
  Past performance does not guarantee future results.
</div>
</body>
</html>"""


_HEADINGS = [("### ", 3), ("## ", 2), ("# ", 1)]


def _md_to_html(text: str) -> str:
    lines = text.split("\n")
    html: list[str] = []
    in_ul = False
    for line in lines:
        matched = False
        for prefix, level in _HEADINGS:
            if line.startswith(prefix):
                if in_ul:
                    html.append("</ul>")
                    in_ul = False
                html.append(f"<h{level}>{line[len(prefix) :]}</h{level}>")
                matched = True
                break
        if matched:
            continue
        if line.startswith("- ") or line.startswith("* "):
            if not in_ul:
                html.append("<ul>")
                in_ul = True
            html.append(f"<li>{line[2:]}</li>")
        else:
            if in_ul:
                html.append("</ul>")
                in_ul = False
            if line.strip():
                line = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", line)
                html.append(f"<p>{line}</p>")
    if in_ul:
        html.append("</ul>")
    return "\n".join(html)
