apiVersion: v1
kind: Service
metadata:
  name: portfolio
  namespace: investments
  labels:
    app: portfolio
spec:
  selector:
    app: portfolio
  ports:
    - port: 8003
      targetPort: 8003
      name: http
  type: ClusterIP
