apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: reports-pvc
  namespace: investments
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 10Gi
