apiVersion: v1
kind: ServiceAccount
metadata:
  name: investments-sa
  namespace: investments
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT:role/investments-assistant-investments-sa-role
